import Link from 'next/link';
import './global.css';
import Navbar from "../components/navbar/Navbar"
import Footer from "../components/footer/Footer"
import { ThemeProvider } from "../context/ThemeContext"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
        <main className='container'>
          <Navbar />
        {children}
        <Footer />
        </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
